/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Citas;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian Lopez
 */
public class IFAgregaryActualizarCitas extends javax.swing.JInternalFrame {
    Controlador_Citas controladorCitas;
    /**
     * Creates new form IFAgregarCitas
     */
    public IFAgregaryActualizarCitas() {
        initComponents();
        controladorCitas= new Controlador_Citas();
        agragarSucursal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        raidB11 = new javax.swing.JRadioButton();
        raidB12 = new javax.swing.JRadioButton();
        raidB13 = new javax.swing.JRadioButton();
        raidB14 = new javax.swing.JRadioButton();
        raidB15 = new javax.swing.JRadioButton();
        raidB16 = new javax.swing.JRadioButton();
        raidB7 = new javax.swing.JRadioButton();
        raidB8 = new javax.swing.JRadioButton();
        raidB9 = new javax.swing.JRadioButton();
        raidB10 = new javax.swing.JRadioButton();
        txtAntiguedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnObCita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVehiculo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxSucursal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setIconifiable(true);

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("PLACA DEL VEHÌCULO");

        buttonGroup1.add(raidB11);
        raidB11.setText("11.00 am");
        raidB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB12);
        raidB12.setText("12.00 md");
        raidB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB13);
        raidB13.setText("13.00 pm");
        raidB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB14);
        raidB14.setText("14.00 pm");
        raidB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB15);
        raidB15.setText("15.00 pm");
        raidB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB16);
        raidB16.setText("16.00 pm");
        raidB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB16ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB7);
        raidB7.setText("07.00 am");
        raidB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB8);
        raidB8.setText("08.00 am");
        raidB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB9);
        raidB9.setText("09.00 am");
        raidB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(raidB10);
        raidB10.setText("10.00 am");
        raidB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raidB10ActionPerformed(evt);
            }
        });

        jLabel5.setText("Antiguedad del vehiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(raidB11)
                    .addComponent(raidB10)
                    .addComponent(raidB9)
                    .addComponent(raidB8)
                    .addComponent(raidB7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(raidB12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(raidB15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(raidB16)
                        .addGap(18, 18, 18)
                        .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(raidB13)
                    .addComponent(raidB14))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raidB7)
                    .addComponent(raidB12))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raidB8)
                    .addComponent(raidB13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raidB9)
                    .addComponent(raidB14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raidB10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(raidB15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raidB11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(raidB16)
                        .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnObCita.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnObCita.setText("OBTENER CITA");
        btnObCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObCitaActionPerformed(evt);
            }
        });

        TablaVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "NOMBRE PROPIETARIO", "AÑO INSCRIPCIÒN", "CEDÙLA PROPIETARIO", "MARCA", "MODELO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaVehiculo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("SUCURSAL DE LA CITA");

        ComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUCURSALES" }));
        ComboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("HORAS DISPONIBLE PARA CITAS");

        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("FECHA DE LA CITA");

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar Cita");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(btnObCita, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnObCita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String hora;

    public String getHora() {
        return hora;
    }
    
    private void raidB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB13ActionPerformed
       if(this.isSelected){
        hora="13 am";
        }
    }//GEN-LAST:event_raidB13ActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void raidB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB7ActionPerformed
        if(this.isSelected){
        hora="7 am";
            
        }
    }//GEN-LAST:event_raidB7ActionPerformed

    private void raidB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB8ActionPerformed
    if(this.isSelected){
        hora=this.getTitle();
        hora="8 am";
        }
    }//GEN-LAST:event_raidB8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (controladorCitas.comprobarPlaca(this)==false) {
            this.txtPlaca.setForeground(Color.green);
            this.controladorCitas.mostrarvehiculo(this);
            this.txtAntiguedad.setText(controladorCitas.antiguedad(this));
        }else{
            IFAgregarVehiculo vehi= new IFAgregarVehiculo();
            FrmMenuPrinc.escritorio.add(vehi);
            this.txtAntiguedad.setText(null);
             DefaultTableModel modelo= (DefaultTableModel) this.TablaVehiculo.getModel();
             modelo.setNumRows(0);
            vehi.show();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void raidB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB9ActionPerformed
    if(this.isSelected){
         hora="9 am";
        }
    }//GEN-LAST:event_raidB9ActionPerformed

    private void raidB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB10ActionPerformed
        if(this.isSelected){
         hora="10 am";
        }
    }//GEN-LAST:event_raidB10ActionPerformed

    private void raidB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB11ActionPerformed
       if(this.isSelected){
         hora="11 am";
        }
    }//GEN-LAST:event_raidB11ActionPerformed

    private void raidB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB12ActionPerformed
     if(this.isSelected){
         hora="12 md";
        }
    }//GEN-LAST:event_raidB12ActionPerformed

    private void raidB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB14ActionPerformed
        if(this.isSelected){
         hora="14 pm";
        }
    }//GEN-LAST:event_raidB14ActionPerformed

    private void raidB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB15ActionPerformed
         if(this.isSelected){
       hora="15 pm";
        }
    }//GEN-LAST:event_raidB15ActionPerformed

    private void raidB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raidB16ActionPerformed
        if(this.isSelected){
         hora="16 pm";
        }
    }//GEN-LAST:event_raidB16ActionPerformed

    private void btnObCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObCitaActionPerformed
        controladorCitas.guardarCita(this);
    }//GEN-LAST:event_btnObCitaActionPerformed

    private void ComboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSucursalActionPerformed
   
        
    }//GEN-LAST:event_ComboBoxSucursalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     controladorCitas.actualizarcita(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controladorCitas.eliminarcita(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      IFBuscarCita buscarcita= new IFBuscarCita();
      FrmMenuPrinc.escritorio.add(buscarcita);
      buscarcita.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
       int cantcaracter=7;
       if(this.txtPlaca.getText().length()==cantcaracter){
       evt.consume();
       }
    }//GEN-LAST:event_txtPlacaKeyTyped
 public void agragarSucursal(){
     ComboBoxSucursal.addItem("CAÑAS");
     ComboBoxSucursal.addItem("LIBERIA");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxSucursal;
    private javax.swing.JTable TablaVehiculo;
    private javax.swing.JButton btnObCita;
    public static javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton raidB10;
    private javax.swing.JRadioButton raidB11;
    private javax.swing.JRadioButton raidB12;
    private javax.swing.JRadioButton raidB13;
    private javax.swing.JRadioButton raidB14;
    private javax.swing.JRadioButton raidB15;
    private javax.swing.JRadioButton raidB16;
    private javax.swing.JRadioButton raidB7;
    private javax.swing.JRadioButton raidB8;
    private javax.swing.JRadioButton raidB9;
    private javax.swing.JTextField txtAntiguedad;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables



    public JRadioButton getRaidB10() {
        return raidB10;
    }

    public JRadioButton getRaidB11() {
        return raidB11;
    }

    public JRadioButton getRaidB12() {
        return raidB12;
    }

    public JRadioButton getRaidB13() {
        return raidB13;
    }

    public JRadioButton getRaidB14() {
        return raidB14;
    }

    public JRadioButton getRaidB15() {
        return raidB15;
    }

    public JRadioButton getRaidB16() {
        return raidB16;
    }

    public JRadioButton getRaidB7() {
        return raidB7;
    }

    public JRadioButton getRaidB8() {
        return raidB8;
    }

    public JRadioButton getRaidB9() {
        return raidB9;
    }

    public JDateChooser getTxtFecha() {
        return txtFecha;
    }

    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    public JComboBox<String> getComboBoxSucursal() {
        return ComboBoxSucursal;
    }

    public JTable getTablaVehiculo() {
        return TablaVehiculo;
    }


}
