/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Citas;
import javax.swing.JTextField;

/**
 *
 * @author Cristian Lopez
 */
public class IFEliminarCitas extends javax.swing.JInternalFrame {
private Controlador_Citas controlCitas;
    /**
     * Creates new form IFEliminarCitas
     */
    public IFEliminarCitas() {
        initComponents();
         controlCitas =new  Controlador_Citas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txteliminarCita = new javax.swing.JTextField();
        btnEliminarCita = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("ID de la cita");

        txteliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteliminarCitaActionPerformed(evt);
            }
        });
        txteliminarCita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txteliminarCitaKeyTyped(evt);
            }
        });

        btnEliminarCita.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarCita.setForeground(new java.awt.Color(0, 51, 51));
        btnEliminarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Eliminar.png"))); // NOI18N
        btnEliminarCita.setText("Eliminar Cita");
        btnEliminarCita.setBorder(new javax.swing.border.MatteBorder(null));
        btnEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnEliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txteliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxteliminarCita() {
        return txteliminarCita;
    }

    private void btnEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCitaActionPerformed
        controlCitas.eliminarCita(this);
    }//GEN-LAST:event_btnEliminarCitaActionPerformed

    private void txteliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteliminarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteliminarCitaActionPerformed

    private void txteliminarCitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteliminarCitaKeyTyped
         char character=evt.getKeyChar();
         int cantcaracter=10;
        if (((character>='A')&&(character<='Z'))||((character>='a')&&(character<='z'))){
            evt.consume();
        }
         if(this.txteliminarCita.getText().length()==cantcaracter){
       evt.consume();
        }
    }//GEN-LAST:event_txteliminarCitaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txteliminarCita;
    // End of variables declaration//GEN-END:variables
}
