/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Cristian Lopez
 */
public class MenuVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuVehiculos
     */
    public MenuVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemAgregarVehiculo = new javax.swing.JMenu();
        agregar = new javax.swing.JMenuItem();
        actualizar = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenuItem();
        menuEliminar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setIconifiable(true);

        itemAgregarVehiculo.setText("Menu Vehiculos");

        agregar.setText("AgregarVehiculo");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        itemAgregarVehiculo.add(agregar);

        actualizar.setText("Actualizar vehículo");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        itemAgregarVehiculo.add(actualizar);

        buscar.setText("Buscar vehículo");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        itemAgregarVehiculo.add(buscar);

        menuEliminar.setText("Eliminar vehiculo");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        itemAgregarVehiculo.add(menuEliminar);

        jMenuBar1.add(itemAgregarVehiculo);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        IFAgregarVehiculo agregar= new IFAgregarVehiculo();
        FrmMenuPrinc.escritorio.add(agregar);
        agregar.show();     
    }//GEN-LAST:event_agregarActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        IFEliminarVehiculo eliminar= new IFEliminarVehiculo();
        FrmMenuPrinc.escritorio.add(eliminar);
        eliminar.show();
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        IFActulizarVehiculo actualizar=new IFActulizarVehiculo();
        FrmMenuPrinc.escritorio.add(actualizar);
        actualizar.show();
    }//GEN-LAST:event_actualizarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        IFBuscarVehiculo buscar =new IFBuscarVehiculo();
        FrmMenuPrinc.escritorio.add(buscar);
        buscar.show();
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizar;
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenu itemAgregarVehiculo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuEliminar;
    // End of variables declaration//GEN-END:variables
}
